vantage-sh/terraform-provider-vantage

go.mod
vantage/client.go

If you create an API token with only write access, the integrations endpoint (understandably) doesn't return anything.
This surfaces itself as empty responses:
```
terraform apply                                                                                                                                    ☁️   pulumi-ce
data.vantage_aws_provider_info.default: Reading...
data.vantage_aws_provider_info.default: Read complete after 0s
Changes to Outputs:
+ provider_info = {
+ additional_resources_policy = ""
+ autopilot_policy            = ""
+ cloudwatch_metrics_policy   = ""
+ external_id                 = ""
+ iam_role_arn                = ""
+ root_policy                 = ""
}
You can apply this plan to save these new output values to the Terraform state, without changing any real …
```

Throw error when token without permissions is used on integration

---

vantage/team_data_source.go
vantage/team_resource.go

Addresses https://github.com/vantage-sh/terraform-provider-vantage/issues/17
I swap all List types for Set types in the team resource. This will (I hope) allow the consumer to pass in a list of tokens, and, if the server responds with the same list of tokens in a different order, allow terraform to be OK with it.
Question - if this is the right approach, is it correct to assume that we should make this change across all of our resources?

Change ListAttribute to SetAttribute to allow for unordered list.

---

examples/resources/vantage_team/provider.tf
vantage/team_resource.go

This fix closes #21. Allows team description to be empty.

fix(team_resource.go): fix to allow description to be empty

---

docs/resources/cost_report.md
docs/resources/dashboard.md
docs/resources/folder.md
docs/resources/saved_filter.md
docs/resources/segment.md
examples/cost_report/main.tf
examples/resources/vantage_cost_report/resource.tf
examples/resources/vantage_dashboard/resource.tf
examples/resources/vantage_folder/resource.tf
examples/resources/vantage_segment/resource.tf
vantage/cost_report_resource.go
vantage/dashboard_resource.go
vantage/folder_resource.go
vantage/saved_filter_resource.go
vantage/segment_resource.go

Addresses https://github.com/vantage-sh/terraform-provider-vantage/issues/23
The immediate issue was bad documentation; the example should have included a `workspace_token` attribute. It now does (as do the examples for other resources).
That said, the issue got me thinking more about the our use of workspace tokens in the API. I've taken the step to make workspace token required for some resources, where before it was an optional parameter. It was optional before because _technically_ there are some access tokens that can intuit which workspace the resource should be assigned to; however, these tokens are not available for use with the Terraform provider, so I have decided that the workspace token should be present. In the case of folders, cost reports and segments, there is a choice of …

Validate workspace token attribute

---

vantage/cost_report_resource.go

addresses #28 
This allows the provider to handle `groupings` and `filter` when the API return back a value such as the empty string, even though no value was passed in in the request.

Let groupings and filter be computed values according to the schema.

---

go.mod
go.sum
vantage/datasource_business_metrics/business_metrics_data_source_gen.go
vantage/resource_anomaly_notification/anomaly_notification_resource_gen.go
vantage/resource_business_metric/business_metric_resource_gen.go
vantage/segments_data_source.go

Also verified in Terraform that you can pass a segment report token as the `cost_report_token` in a budget resource.

feat: Expose report_token in the segments data source.

---

vantage/segment_resource.go
vantage/segments_data_source.go

- Adds `ReportToken` to the segment resource model.
- In the data source, reads the `ReportToken` field from the API response into the terraform state object.

fix: Add ReportToken field to segment resource; parse field in Read()

---

.github/workflows/release.yml

Changes in cli options from v1 to v2 caused our terraform publish to fail

Update goreleaser command and pin version

---

vantage/cost_report_resource.go

Paired on this with @whereandy. 
**What does this fix?**
When trying to patch a cost report resource's `date_interval`, the `start_date` and `end_date` are being included because they are part of the TF state. This results in the API overwriting the provided `date_interval` field with the value `custom`. Incompatibility is mentioned in the [API docs](https://vantage.readme.io/reference/updatecostreport).

fix: Don't set dates when date interval is not custom.

---

vantage/access_grant_resource.go
vantage/anomaly_notification_resource.go
vantage/billing_rule_resource.go
vantage/budget_resource.go
vantage/business_metric_resource.go
vantage/cost_report_resource.go
vantage/dashboard_resource.go
vantage/folder_resource.go
vantage/managed_account_resource.go
vantage/report_notification_resource.go
vantage/saved_filter_resource.go
vantage/segment_resource.go
vantage/team_resource.go
vantage/virtual_tag_config_resource.go

Also did a little housekeeping, adding interface checks for all the resources and made them all the same format (that which was present in [the tf docs](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-resource-import) for consistency).
An example:
1. Previously created resource to show expected state.
2. Remove from TF state so it no longer knows about it.
3. `terraform plan` to show the create action for the "new" resource.
4. `terraform import` using the token.
5. `terraform plan` showing the imported resource means state reflects expectation and no action required.
```
➜  terraform state show vantage_cost_report.demo_report
resource "vantage_cost_report" "demo_report" {
chart_type          = "line"
date_bin            = …
```

Allow users to import resources.

---

generator.yaml
vantage/resource_budget/budget_resource_gen.go

`include_performance` is a parameter you can use when getting budgets that for some reason got added as an attribute to the budget model by `tfplugingen-openapi generate`. This explicitly omits that attribute during generation.

ignore include_performance when generating the BudgetModel

---

vantage/kubernetes_efficiency_reports_data_source.go

Handles the groupings as they are passed from the API as a comma separated list and not an array as the `ListValueFrom` expects.

fix: Split groupings for list.

---

vantage/budget_resource_model.go
vantage/kubernetes_efficiency_report_resource_test.go
vantage/kubernetes_efficiency_reports_data_source.go
vantage/kubernetes_efficiency_reports_data_source_test.go

TakeTwo was seeing this:
```
Error: List Type Validation Error
with data.vantage_kubernetes_efficiency_reports.all,
An unexpected error was encountered trying to validate an attribute value.
This is always an error in the provider. Please report the following to the
provider developer:
expected List value, received tftypes.Value with value:
tftypes.String<"cluster_id">
```
when trying to apply this TF:
```
data "vantage_kubernetes_efficiency_reports" "all" {}
```
I tracked it down to the fact that I was using the resource struct to hold the attributes for the data source. This was an error because groupings in the resource assumes it is a list, but the data source requires it to be a string. So, they are not interchangeable.
In addition, this error did not show up earlier because of lack …

fix: Dont use the resource model struct for the data source.

---

vantage/access_grant_resource_test.go
vantage/workspaces_data_source_test.go

- Verifies team token usage for access grants
- Updates workspace data source test to check that at least one workspace is returned
Related to: 
https://github.com/vantage-sh/core/pull/11244

chore: Update tests

---

vantage/report_notification_resource.go
vantage/report_notification_resource_test.go

This came out of investigating https://www.notion.so/vantagesh/Wunderkind-Terraform-Error-199e0cdf383080869211f36e27a72784?pvs=4
Even though the fix for that customer task was in `core`, this part of the code made me realize that we were not allowing the Terraform provider to set Slack channels in the report notification. This PR adds that in, as well as acceptance test coverage of this resource.

feat: Add recipient_channel attribute to the report_notification resource.

---

vantage/access_grant_resource_test.go

Removes the skip in the access grants test. This should work now for the account we are testing against in core's CI

Unskip the skipped test

---

go.mod
go.sum
vantage/business_metric_resource.go
vantage/business_metric_resource_model.go
vantage/business_metric_resource_test.go
vantage/business_metrics_data_source.go
vantage/datasource_business_metrics/business_metrics_data_source_gen.go
vantage/resource_business_metric/business_metric_resource_gen.go

Changing how we handle creation of business metrics via Terraform. Now that `values` is not returned in the API response, when  a user specifies `values` in the Terraform code, we pass that directly to the state of the resource _after_ the API has returned, so that the state of `values` is avoids being "unknown" after the operation. In most other interactions with the API, the value is set when reading the payload; here, we set it manually.

Business Metrics resource change

---

vantage/cost_report_resource.go
vantage/cost_report_resource_test.go

These values need to be allowed to be handled as computed properties that can change from month to month. The inclusion of the `stringplanmodifier.UseStateForUnknown(),` for these fields caused problems because it is meant to be used "when it is known that an unconfigured value will remain the same after a resource update." [link](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier#UseStateForUnknown)
This is in response to this error:
I havent had a chance to see the terraform code this error was occurring in, but my hunch is that when we crossed the month barrier, the start_date and end_date values for a report changed when the date interval was set to last_x_months.

Remove the planmodifier from start_date and end_date.

---

examples/cost_report/main.tf
go.mod
go.sum
vantage/cost_report_resource.go
vantage/cost_report_resource_test.go

To unset the groupings attribute, we pass an empty string as the value in the API request. The API then responds with a payload that has a null value for the groupings. 
There is a known issue in the provider framework when attempting to set a previously-known-value to null : https://discuss.hashicorp.com/t/after-applying-this-test-step-and-performing-a-terraform-refresh-the-plan-was-not-empty/42835
The hack solution is to store the groupings value as an empty string in terraform state when it has been removed.

fix: Allow unset of groupings by storing as empty string.

---

vantage/kubernetes_efficiency_report_resource_model.go
vantage/kubernetes_efficiency_report_resource_test.go

Treat start_date and end_date as strings, rely on server for validation and returning the dates in the expected format of YYYY-MM-DD.
The companion to this is https://github.com/vantage-sh/core/pull/12000

Fix parsing of start_date and end_date in kubernetes efficiency report resource

---

.github/workflows/test.yml

- External contributions must be triggered manually
- No concurrency; only one `tests-acceptance` job permitted at a time
completes ENG-219

chore: Run + Require successful test runs for PRs.

---

vantage/cost_report_resource.go
vantage/cost_report_resource_test.go
vantage/report_notification_resource_test.go

If you omit the date_bin and chart_type attributes from the vantage_cost_report, calling ValueStringPointer() on those attributes will return "" if the value is unknown. This "" value is not accepted by the API for these attributes, causing 400.
Now, we check if the value is not null and not unknown before setting its value in the request body. That way, the request body will correctly send a null value for chart_type or date_bin if you dont include it.

fix: Do not include chart_type or date_bin in the create/update requests if not specified.
